"""Added isFake field to User model

Revision ID: 051a689625ca
Revises: c6d17a2c6058
Create Date: 2025-02-03 22:11:39.275186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '051a689625ca'
down_revision = 'c6d17a2c6058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isFake', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('isFake')

    # ### end Alembic commands ###
