"""Add player metadata fields for ESPN-style details

Revision ID: bae6654dba96
Revises: 1239e3b841aa
Create Date: 2025-07-09 00:06:10.943212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bae6654dba96'
down_revision = '1239e3b841aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('birthdate', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('college', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('draft_info', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='Active', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('draft_info')
        batch_op.drop_column('college')
        batch_op.drop_column('birthdate')
        batch_op.drop_column('weight')
        batch_op.drop_column('height')

    # ### end Alembic commands ###
