"""Initial migration with full Player schema

Revision ID: d65d7ba3a17b
Revises: 
Create Date: 2025-07-09 12:09:12.195440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd65d7ba3a17b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('position', sa.String(length=20), nullable=False),
    sa.Column('team', sa.String(length=50), nullable=False),
    sa.Column('height', sa.String(length=10), nullable=True),
    sa.Column('weight', sa.String(length=10), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('college', sa.String(length=100), nullable=True),
    sa.Column('draft_info', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='Active', nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('profilePic', sa.String(length=200), nullable=True),
    sa.Column('isFake', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('rankings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_rankings_player_id_players')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_rankings_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rankings'))
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_reviews_player_id_players')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reviews_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('rankings')
    op.drop_table('users')
    op.drop_table('players')
    # ### end Alembic commands ###
